"""Append-only markdown decision log per agent (v2.5 T1.11).

Plan §T1.11: every advice gets a markdown entry under
``/srv/iic/decision_logs/<agent_slug>.md`` with HTML-comment delimiters.
The Backtest agent's `Reflector` writes a 2-4 sentence post-hoc
reflection back into the source agent's entry on every realised outcome.

Atomicity: writes are temp-file + ``os.replace`` so a kill mid-write can
never corrupt the file. Concurrency: per-agent ``asyncio.Lock`` so two
DAG nodes appending advice for the same agent serialise.

The HTML-comment delimiter format is parser-friendly — one regex
extracts every entry (used by the dashboard and by the Backtest reflector
to find the entry it needs to amend).
"""

from __future__ import annotations

import asyncio
import os
import re
import tempfile
from collections.abc import Iterable, Mapping
from dataclasses import dataclass, field
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

DEFAULT_LOG_ROOT = Path("/srv/iic/decision_logs")


@dataclass(frozen=True, slots=True)
class DecisionLogEntry:
    advice_id: str
    agent: str
    issued_at: datetime
    rating: str
    thesis: str
    evidence_urls: tuple[str, ...] = ()
    reflection: str | None = None

    def to_markdown(self) -> str:
        return _render_entry(self)


_BEGIN_RE = re.compile(
    r"<!-- BEGIN entry id=(?P<id>[^\s]+)\s+agent=(?P<agent>[^\s>]+)\s*-->"
)
_END_RE = re.compile(r"<!-- END entry -->")
_ENTRY_RE = re.compile(
    r"<!-- BEGIN entry id=(?P<id>[^\s]+)\s+agent=(?P<agent>[^\s>]+)\s*-->"
    r"(?P<body>.*?)"
    r"<!-- END entry -->",
    re.DOTALL,
)
_REFLECTION_DELIM_BEGIN = "<!-- reflection -->"
_REFLECTION_DELIM_END = "<!-- /reflection -->"


@dataclass(slots=True)
class DecisionLog:
    """Per-agent append-only markdown log under ``root / f"{agent_slug}.md"``."""

    root: Path = DEFAULT_LOG_ROOT
    _locks: dict[str, asyncio.Lock] = field(default_factory=dict, init=False)

    def path_for(self, agent_slug: str) -> Path:
        return self.root / f"{agent_slug}.md"

    def _lock(self, agent_slug: str) -> asyncio.Lock:
        lock = self._locks.get(agent_slug)
        if lock is None:
            lock = asyncio.Lock()
            self._locks[agent_slug] = lock
        return lock

    async def append(self, entry: DecisionLogEntry) -> Path:
        """Atomically append `entry` to the agent's log file."""
        path = self.path_for(entry.agent)
        path.parent.mkdir(parents=True, exist_ok=True)
        async with self._lock(entry.agent):
            existing = path.read_text() if path.exists() else _header_for(entry.agent)
            new_body = existing + _render_entry(entry)
            _atomic_write(path, new_body)
        return path

    async def attach_reflection(
        self,
        agent: str,
        advice_id: str,
        reflection: str,
    ) -> bool:
        """Insert (or replace) the reflection block on the matching entry.

        Returns True when the entry was found + updated; False otherwise.
        """
        path = self.path_for(agent)
        if not path.exists():
            return False
        async with self._lock(agent):
            text = path.read_text()
            updated, found = _inject_reflection(text, advice_id, agent, reflection)
            if not found:
                return False
            _atomic_write(path, updated)
        return True

    def iter_entries(self, agent: str) -> Iterable[Mapping[str, Any]]:
        """Yield every entry in the agent's log as a dict.

        Synchronous because the dashboard calls this from a sync handler.
        """
        path = self.path_for(agent)
        if not path.exists():
            return iter(())
        return _parse_entries(path.read_text())


def _atomic_write(path: Path, body: str) -> None:
    """Temp-file + os.replace — survives a kill mid-write."""
    fd, tmp_path = tempfile.mkstemp(dir=str(path.parent), prefix=".tmp.")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            f.write(body)
            f.flush()
            os.fsync(f.fileno())
        os.replace(tmp_path, path)
    except Exception:
        try:
            os.unlink(tmp_path)
        except OSError:
            pass
        raise


def _header_for(agent: str) -> str:
    return (
        f"# {agent} decision log\n\n"
        f"> Append-only markdown — every advice this agent emits is logged here.\n"
        f"> Generated by `data_lake.decision_log` (v2.5 T1.11). Do not edit by hand.\n\n"
    )


def _render_entry(entry: DecisionLogEntry) -> str:
    iso = entry.issued_at.astimezone(UTC).isoformat()
    evid_md = ""
    if entry.evidence_urls:
        evid_md = "\n**Evidence:**\n" + "\n".join(f"- {u}" for u in entry.evidence_urls) + "\n"
    refl_md = ""
    if entry.reflection:
        refl_md = (
            f"\n{_REFLECTION_DELIM_BEGIN}\n"
            f"**Reflection:** {entry.reflection.strip()}\n"
            f"{_REFLECTION_DELIM_END}\n"
        )
    return (
        f"\n<!-- BEGIN entry id={entry.advice_id} agent={entry.agent} -->\n"
        f"## {iso} — {entry.rating}\n\n"
        f"{entry.thesis.strip()}\n"
        f"{evid_md}"
        f"{refl_md}"
        f"<!-- END entry -->\n"
    )


def _inject_reflection(
    text: str, advice_id: str, agent: str, reflection: str
) -> tuple[str, bool]:
    """Return (new_text, found). Replaces any existing reflection block."""
    pattern = re.compile(
        rf"<!-- BEGIN entry id={re.escape(advice_id)}\s+agent={re.escape(agent)}\s*-->"
        rf"(?P<body>.*?)"
        rf"<!-- END entry -->",
        re.DOTALL,
    )
    m = pattern.search(text)
    if m is None:
        return text, False

    body = m.group("body")
    # Strip any prior reflection block.
    body = re.sub(
        rf"{re.escape(_REFLECTION_DELIM_BEGIN)}.*?{re.escape(_REFLECTION_DELIM_END)}\n?",
        "",
        body,
        flags=re.DOTALL,
    )
    body = body.rstrip("\n") + (
        f"\n{_REFLECTION_DELIM_BEGIN}\n"
        f"**Reflection:** {reflection.strip()}\n"
        f"{_REFLECTION_DELIM_END}\n"
    )
    new_entry = (
        f"<!-- BEGIN entry id={advice_id} agent={agent} -->"
        f"{body}"
        f"<!-- END entry -->"
    )
    return text[: m.start()] + new_entry + text[m.end():], True


def _parse_entries(text: str) -> Iterable[Mapping[str, Any]]:
    for m in _ENTRY_RE.finditer(text):
        body = m.group("body")
        refl_match = re.search(
            rf"{re.escape(_REFLECTION_DELIM_BEGIN)}\s*\*\*Reflection:\*\*\s*(?P<r>.*?)"
            rf"{re.escape(_REFLECTION_DELIM_END)}",
            body,
            re.DOTALL,
        )
        yield {
            "advice_id": m.group("id"),
            "agent": m.group("agent"),
            "body": body.strip(),
            "reflection": (refl_match.group("r").strip() if refl_match else None),
        }
