#!/usr/bin/env bash
#
# IIC v2.5 — generate a DEV-mode .env from .env.example.
#
# Fills in random passwords for the local datastores (postgres / minio /
# restic / etc.) and leaves third-party API keys blank. With blank API
# keys the agents still boot — calls just short-circuit (LLM cost-skip,
# notifier durable-redelivery, etc.).
#
# This is NOT how prod secrets are managed. Production uses sops + age
# (see workflow 31 §3.1 + .sops.yaml). For prototype testing on a
# trusted LAN, plaintext .env in the repo working tree is fine because
# .gitignore excludes it.
#
# Usage:
#   bash deploy/bootstrap-secrets.sh                # writes ./.env
#   bash deploy/bootstrap-secrets.sh --force        # overwrite existing .env
#   bash deploy/bootstrap-secrets.sh --print-only   # dry-run; print to stdout

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
ENV_FILE="${REPO_ROOT}/.env"
TEMPLATE="${REPO_ROOT}/.env.example"

FORCE=0
PRINT_ONLY=0
for arg in "$@"; do
  case "${arg}" in
    --force)      FORCE=1 ;;
    --print-only) PRINT_ONLY=1 ;;
    -h|--help)
      sed -n '2,16p' "${BASH_SOURCE[0]}" | sed 's/^# \?//'
      exit 0
      ;;
    *)
      echo "Unknown argument: ${arg}" >&2; exit 64 ;;
  esac
done

if [[ ! -f "${TEMPLATE}" ]]; then
  echo "missing template: ${TEMPLATE}" >&2
  exit 1
fi

if [[ -f "${ENV_FILE}" && "${FORCE}" -eq 0 && "${PRINT_ONLY}" -eq 0 ]]; then
  echo ".env already exists; pass --force to overwrite, or edit it by hand."
  exit 0
fi

# 24 chars of base64 → 18 bytes of entropy. Plenty for local passwords.
gen_pw() { openssl rand -base64 18 | tr -d '/+=' | head -c 24; }

POSTGRES_PASSWORD="$(gen_pw)"
POSTGRES_PASSWORD_RO="$(gen_pw)"
POSTGRES_PASSWORD_MIGRATION="$(gen_pw)"
MINIO_ROOT_PASSWORD="$(gen_pw)"
RESTIC_PASSWORD="$(gen_pw)"
PG_RO_PASSWORD="${POSTGRES_PASSWORD_RO}"

# Build the new .env in a temp file so we never leave a half-written one.
TMP="$(mktemp)"
trap 'rm -f "${TMP}"' EXIT

# Take the template verbatim, then patch the keys we know how to fill.
cp "${TEMPLATE}" "${TMP}"

# ${TMP} edits: substitute the empty-RHS lines with our generated values.
sed -i.bak \
  -e "s|^POSTGRES_PASSWORD=\$|POSTGRES_PASSWORD=${POSTGRES_PASSWORD}|" \
  -e "s|^MINIO_ROOT_PASSWORD=\$|MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}|" \
  -e "s|^RESTIC_PASSWORD=\$|RESTIC_PASSWORD=${RESTIC_PASSWORD}|" \
  -e "s|^IIC_PG_RO_PASSWORD=\$|IIC_PG_RO_PASSWORD=${PG_RO_PASSWORD}|" \
  "${TMP}"
rm -f "${TMP}.bak"

# Append the keys the template doesn't have a placeholder for.
{
  echo ""
  echo "# ---- generated by deploy/bootstrap-secrets.sh ----"
  echo "POSTGRES_PASSWORD_RO=${POSTGRES_PASSWORD_RO}"
  echo "POSTGRES_PASSWORD_MIGRATION=${POSTGRES_PASSWORD_MIGRATION}"
  # PG DSNs the FUTU audit anchor script expects.
  echo "IIC_PG_DSN_APP=postgresql://\${POSTGRES_USER}:${POSTGRES_PASSWORD}@\${POSTGRES_HOST}:\${POSTGRES_PORT}/\${POSTGRES_DB}"
  echo "IIC_PG_DSN_RO=postgresql://iic_ro:${POSTGRES_PASSWORD_RO}@\${POSTGRES_HOST}:\${POSTGRES_PORT}/\${POSTGRES_DB}"
  echo ""
  echo "# Where the orchestrator + agents look for feature flags YAML."
  echo "IIC_FEATUREFLAGS_PATH=/srv/iic/featureflags/flags.yaml"
  echo ""
  echo "# Disable INTEL_AUTOSTART for first-run so the intelligence agent"
  echo "# doesn't try to fetch news from APIs whose keys aren't set yet."
  echo "INTEL_AUTOSTART=0"
  echo ""
  echo "# Lake DSN — the LakeConfig resolver builds this from POSTGRES_*."
  echo "POSTGRES_USER_RO=iic_ro"
  echo "POSTGRES_USER_MIGRATION=iic_migration"
} >> "${TMP}"

if [[ "${PRINT_ONLY}" -eq 1 ]]; then
  cat "${TMP}"
  exit 0
fi

mv "${TMP}" "${ENV_FILE}"
trap - EXIT
chmod 600 "${ENV_FILE}"

# Cache the generated passwords in a marker file the migrations script
# reads back. We never echo passwords to stdout.
mkdir -p "${REPO_ROOT}/.deploy"
chmod 700 "${REPO_ROOT}/.deploy"
cat > "${REPO_ROOT}/.deploy/postgres.env" <<EOF
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_PASSWORD_RO=${POSTGRES_PASSWORD_RO}
POSTGRES_PASSWORD_MIGRATION=${POSTGRES_PASSWORD_MIGRATION}
EOF
chmod 600 "${REPO_ROOT}/.deploy/postgres.env"

echo "Wrote ${ENV_FILE} (mode 600)."
echo "  Generated random passwords for: postgres / minio / restic / pg_ro."
echo "  Third-party API keys (DEEPSEEK_API_KEY, etc.) are LEFT BLANK."
echo "  See DEPLOYMENT.md for which agents need which keys."
